### ISSUE TITLE
2.6.3

### ISSUE THREAD

**Issue by rnc** [FasterXML/jackson-parent#2]
jackson-core has had a release of 2.6.3 but there is no corresponding release of jackson-parent. If we want to build jackson in a repeatable build system and the versions are not correctly aligned (i.e. everything using 2.6.3) then we would end up having to build 2.6.3, 2.6.2, etc etc.

**Comment by cowtowncoder** [comment]
Jackson parent is not designed to follow the numbering scheme; it is not meant to be version synchronized. It is likely that a different minor version will be released across Jackson releases, but even that may not be necessary. Parent pom is not meant to be publicly used for components other than direct Jackson extensions; and for these explicit version number seems more useful than forced generation of unchanging parent pom versions.

If you feel this is an important change feel free to bring it up on `jackson-dev` mailing list, but there are no current plans to change this.

**Comment by rnc** [comment]
Thanks for the reply. The same problem exists in jackson-core e.g. the release is 2.6.3 but then depends upon a release of jackson-parent 2.6.1. 
Releases surely should be using one consistent set of versions. This makes rebuilding in a controlled environment much harder than normal maven projects - i.e. we then have to end up building multiple versions of jackson rather than just 2.6.3. Take for example Drools (https://github.com/droolsjbpm) ; when they release that is synchronised across the relevant projects.

**Comment by cowtowncoder** [comment]
No, I don't think you were reading what I said. `jackson-parent` is not a publicly available artifact, or something that was meant for anything that core Jackson components to rely on. Your build system should not need it -- jackson components explicitly specify parent version they need, not anyone else.
This is not an ovesight but decision: parent pom changes rarely, and there is no benefit from forcing artificially differing versions for the same parent pom.

All parent pom defines are baseline settings for actual poms by components: there is no code, interfaces, nothing else. There is no requirement that same versions of jackson components use same parent. There is no strict requirement that they would even have to use same parent pom, or any parent pom. It is just for convenience, for reducing complexity of child poms.

**Comment by rnc** [comment]
With all due respect, jackson parent _is_ a publicly available artifact : https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/

Even if the issue with the parent is ignored, there are still multiple version inconsistencies throughout Jackson - are there any plans to fix those to bring it inline with Maven best practices?

**Comment by cowtowncoder** [comment]
For annotations, _all patch versions of given minor version are identical_. There is no version mismatch whatsoever. The only reason -- and one I seem to get to regret now, thanks you requests like this -- to ever even publishing patch versions has been to help users simplify their version references. So that they can indeed refer to same PATCH version of annotation as core, databind and others _despite it NOT being necesssary_: 2.6.2 is identical, content-wise, to 2.6.0.
Annotations is EXPLICITLY kept identical in that no signature differences are allowed.

As to parent pom, it DOES NOT HAVE TO MATCH BETWEEN COMPONENTS. There is absolutely no reason or requirement for parent pom version to need to match component version; or parent poms of sibling jackson components to use parent pom version. No need at all.

As to not being public obviously it has to be accessible from public Maven repository to be able to build components, but it is not MEANT to be public artifact relied on by anything outside of Jackson  modules.

This is the last comment where I explain the same thing over and over: you are free to disagree all you want, but I see no problem to fix here.
